version: '3'

services:
  api-forwarder:
    build: .
    container_name: api-forwarder
    ports:
      - "6667:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ENABLE_FILE_OPERATIONS=true
      - ADMIN_TOKEN=admin

    volumes:
      - ./logs:/app/logs
